# Generated by Django 6.0 on 2025-12-07 22:27

import datetime
import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Короткое название места (дом, офис, парк и т.п.).', max_length=100, unique=True, verbose_name='название места')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание места (по желанию).', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'список мест',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Время, когда необходимо выполнять привычку.', verbose_name='время')),
                ('action', models.CharField(help_text='Что именно нужно делать: пить воду, гулять, медитировать и т.д.', max_length=255, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Отметьте, если эта привычка является приятной (используется как награда).', verbose_name='приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Как часто выполнять привычку (в днях). Допустимо от 1 до 7 (не реже, чем раз в неделю).', validators=[habits.validators.validate_periodicity_1_to_7_days], verbose_name='периодичность (дни)')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение, если НЕ используется приятная привычка.', max_length=255, verbose_name='вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=60), help_text='Сколько времени требуется на выполнение привычки.', validators=[habits.validators.validate_duration_max_120_seconds], verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='Показывать ли привычку другим пользователям.', verbose_name='публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, являющаяся наградой.', limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_for', to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('place', models.ForeignKey(blank=True, help_text='Место, где выполняется привычка. Можно оставить пустым.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='habits.place', verbose_name='место')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('-created_at',),
            },
        ),
    ]
