# Generated by Django 6.0 on 2025-12-28 17:20

import datetime
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(seconds=60),
                help_text="Сколько времени требуется на выполнение привычки (максимум 120 секунд).",
                null=True,
                validators=[habits.validators.validate_duration_max_120_seconds],
                verbose_name="время на выполнение",
            ),
        ),
    ]
