# Generated by Django 6.0 on 2025-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_telegramlinktoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramlinktoken",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "токен привязки Telegram",
                "verbose_name_plural": "токены привязки Telegram",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramprofile",
            options={
                "ordering": ("user",),
                "verbose_name": "Telegram-профиль",
                "verbose_name_plural": "Telegram-профили",
            },
        ),
        migrations.AlterField(
            model_name="telegramlinktoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создан"),
        ),
        migrations.AlterField(
            model_name="telegramlinktoken",
            name="expires_at",
            field=models.DateTimeField(
                help_text="Дата и время, после которых токен считается просроченным.",
                verbose_name="действителен до",
            ),
        ),
        migrations.AlterField(
            model_name="telegramlinktoken",
            name="is_used",
            field=models.BooleanField(
                default=False,
                help_text="Отмечается True после успешной привязки Telegram.",
                verbose_name="использован",
            ),
        ),
        migrations.AlterField(
            model_name="telegramlinktoken",
            name="token",
            field=models.CharField(
                help_text="Одноразовый токен для привязки Telegram.",
                max_length=128,
                unique=True,
                verbose_name="токен",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="chat_id",
            field=models.CharField(
                help_text="Идентификатор чата, куда отправляются уведомления.",
                max_length=64,
                unique=True,
                verbose_name="Telegram chat ID",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Если выключено — напоминания в Telegram не отправляются.",
                verbose_name="уведомления включены",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Имя пользователя в Telegram (@username), если доступно.",
                max_length=255,
                verbose_name="Telegram username",
            ),
        ),
    ]
